apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-reservaciones
  labels:
    app: api-reservaciones
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-reservaciones
  template:
    metadata:
      labels:
        app: api-reservaciones
    spec:
      containers:
      - name: api-reservaciones
        image: acrsanjoylaoprod001.azurecr.io/api-reservaciones:latest
        ports:
        - containerPort: 9000